[phases.setup]
nixPkgs = ["nodejs_24", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm prisma generate", "pnpm exec nx build api"]

[start]
cmd = "node dist/api/main.js"